export class ProductContainerData {
  _id: string;
  sn : number;
  exportN : number;
  contNo : string;
  sealNo : string;
  contType : string;
  size :string;
  teu : number;
  noOfPackage : number;
  grossWt : number;
  netWt : number;
  tareWt : string;
  pkgMatGrossWt : string;
  lotNo : string;
  m3 : number;
  vgm : string;
  uom : string;
  vgmMethod : string;
  capacity : string;
  depot : string;
  batchNumber : string;
  noOfPalette : string;
  verifiedDt : Date;
  emptyReleaseDate : Date;
  emptyPickup : Date;
  gateIn : Date;
  vesselLoad : Date;
  vesselDeparture : Date;
  vesselArrival : Date;
  unloadedFromVessel : Date;
  gatedOut : Date;
  returned : Date;
  // verifiedDt : Date = new Date();
  // emptyReleaseDate : Date = new Date();
  // emptyPickup : Date = new Date();
  // gateIn : Date = new Date();
  // vesselLoad : Date = new Date();
  // vesselDeparture : Date = new Date();
  // vesselArrival : Date = new Date();
  // unloadedFromVessel : Date = new Date();
  // gatedOut : Date = new Date();
  // returned : Date = new Date();
}
